# Generated by Django 4.1.7 on 2023-11-21 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poblacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=100)),
                ('departamentos', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Salario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bruto_cobrar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pago_extra', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PuestoLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cargo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('salario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelado.salario')),
            ],
        ),
        migrations.CreateModel(
            name='FabricaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fabrica', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('cod_postal', models.CharField(max_length=100)),
                ('poblacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='modelado.poblacion')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('dni', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('fabrica_laboral', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='modelado.fabricalaboral')),
                ('puesto_laboral', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='modelado.puestolaboral')),
            ],
        ),
    ]
