# Generated by Django 4.1.7 on 2023-12-02 05:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ultimo_descuento',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
