# Generated by Django 4.1.7 on 2023-11-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alguna', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='cancion',
        ),
        migrations.AddField(
            model_name='playlist',
            name='cancion',
            field=models.ManyToManyField(to='alguna.canciones'),
        ),
    ]
