# Generated by Django 4.1.7 on 2023-12-03 00:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('celular', models.CharField(max_length=9)),
                ('direccion', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
